print("Hello World")
print("Hello again")
print("I Like typing this")
print("tihs is fun")
print("'Yyay! Printing.'")
print("I'd much rather you 'not'")
print(' I "said" do not thoch this')
print("Hello","World")